name: Update Events data via Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MCM_PAT }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script
        env:
          MCM_APP_ID: ${{ secrets.MCM_APP_ID }}
          MCM_INSTALLATION_ID: ${{ secrets.MCM_INSTALLATION_ID }}
          MCM_APP_PRIVATE_KEY: ${{ secrets.MCM_APP_PRIVATE_KEY }}
          IS_PRODUCTION: ${{ vars.IS_PRODUCTION }}
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --cached --quiet && git diff --quiet; then
              echo "No changes to commit"
          else
              CHANGES=$(git diff --name-only)
              git add -A
              git commit -m "${CHANGES}"
          fi

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MCM_PAT }}
          branch: main
